image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - testar
  - construir
  - implantar-develop

before_script:
  - pwd

qa-aplicacao:
  stage: testar
  script:
    - dotnet test

contruir-aplicacao:
  stage: construir
  when: on_success
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - ./artefatos
    untracked: false
    expire_in: 3 mins 4 sec
    when: always
  cache:
    key: meu-cache
    policy: push
    paths:
      - ./artefatos
  script:
    - dotnet build -c Release -o ./artefatos
    - ls ./artefatos

develop-aplicacao:
  stage: implantar-develop
  when: on_success
  cache:
    key: meu-cache
    policy: pull
    paths:
      - ./artefatos
  script:
    - dotnet publish -c Release -o ./develop
    - ls ./develop
  environment:
    name: develop
  only:
    - develop